# Generated by Django 5.2.6 on 2025-09-19 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id_ride", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ROUTE", "en-route"),
                            ("PICKUP", "pickup"),
                            ("DROPOFF", "dropoff"),
                        ],
                        default="PICKUP",
                        max_length=20,
                    ),
                ),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField()),
                ("dropoff_longitude", models.FloatField()),
                ("pickup_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "admin"),
                            ("DRIVER", "driver"),
                            ("RIDER", "rider"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Ride_Event",
            fields=[
                ("id_ride_event", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ride_events",
                        to="ridelist.ride",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ride",
            name="id_driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rides_as_driver",
                to="ridelist.user",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="id_rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rides_as_rider",
                to="ridelist.user",
            ),
        ),
    ]
